# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:          /
  param:        { module: movie, action: index }

buy_movie:
  url:          /:sf_culture/movies/buy/:slug
  param:        { module: order, action: buy }
  requirements: { sf_culture: en|fr }

category:
  url:          /:sf_culture/movies/:category
  param:        { module: movie, action: category }
  requirements: { sf_culture: en|fr }

search:
  url:          /:sf_culture/search
  param:        { module: movie, action: search }
  requirements: { sf_culture: en|fr }
