# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:          /
  param:        { module: movie, action: index }

account:
  url:          /:sf_culture/account
  param:        { module: account, action: index }
  requirements: { sf_culture: en|fr }

order:
  url:          /:sf_culture/order
  param:        { module: order, action: order }
  requirements: { sf_culture: en|fr }

cart_add:
  url:          /:sf_culture/movies/buy/:slug
  param:        { module: order, action: addMovie }
  requirements: { sf_culture: en|fr }

category:
  url:          /:sf_culture/movies/:category
  param:        { module: movie, action: category }
  requirements: { sf_culture: en|fr }

search:
  url:          /:sf_culture/search
  param:        { module: movie, action: search }
  requirements: { sf_culture: en|fr }

sf_guard_register:
    url:          /:sf_culture/register
    param:        { module: sfGuardRegister, action: index }
    requirements: { sf_culture: en|fr }

sf_guard_signout:
    url:          /:sf_culture/logout
    param:        { module: sfGuardAuth, action: signout }
    requirements: { sf_culture: en|fr }

sf_guard_signin:
    url:          /:sf_culture/login
    param:        { module: sfGuardAuth, action: signin }
    requirements: { sf_culture: en|fr }
