test:
  doctrine:
    param:
      dsn:      sqlite::memory
      dsn:      mysql:host=localhost;dbname=sl_movie_store_test

all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn:      mysql:host=localhost;dbname=sl_movie_store
      username: root
      password: ~
